Repository apimatic/apimatic-js-runtime, pull requests merged in 2024-12, with the labels that each got.

#197 docs: update README to document Mono Repo versioning
  README.md
Labels: documentation

#194 build(version-bump): update dependency version
  package.json
  packages/authentication-adapters/package.json
  packages/axios-client-adapter/package.json
  packages/convert-to-stream/package.json
  packages/core-interfaces/package.json
  packages/core/package.json
  packages/core/src/errors/responseValidationError.ts
  packages/file-wrapper/package.json
  packages/http-headers/package.json
  packages/http-query/package.json
  packages/oauth-adapters/package.json
  packages/schema/package.json
  packages/test-utilities/package.json
  packages/xml-adapter/package.json
  yarn.lock
Labels: dependencies

#196 chore(deps): add dependabot configuration file
  .github/dependabot.yml
  .github/workflows/main.yml
Labels: dependencies

#208 fix(workflow): correct workflow file
  .github/workflows/main.yml
Labels: bug
